<Project>

	<PropertyGroup>
		<ImplicitUsings>disable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>preview</LangVersion>

		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>full</TrimMode>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<DefineConstants>$(DefineConstants);LINUX</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
		<DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-macos'">
		<DefineConstants>$(DefineConstants);MACOS</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(DEBUG)' != ''">
		<DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
	</PropertyGroup>

</Project>
