<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-android;net10.0-windows</TargetFrameworks>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Calculator.cs</PackageId>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<PublishSelfContained>true</PublishSelfContained>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<TrimmerRootAssembly>Calculator</TrimmerRootAssembly>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Eval.cs" Version="0.11.0" />
		<ProjectReference Include="../Raylib-cs/Raylib-cs.csproj">
			<ExcludeAssets Condition="'$(TargetFramework)' == 'net10.0-android'">native</ExcludeAssets>
		</ProjectReference>
		<EmbeddedResource Include="Resources/*.png">
			<LogicalName>$([System.String]::new('%(FileName)%(Extension)'))</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="../CalculatorAndroid/Resources/mipmap-xxxhdpi/appicon.png">
			<LogicalName>$([System.String]::new('%(FileName)%(Extension)'))</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Resources/iosevka-regular.ttf" />
	</ItemGroup>

	<!-- APIKEY -->
	<PropertyGroup Condition="Exists('APIKEY')">
		<DefineConstants>$(DefineConstants);HAS_APIKEY</DefineConstants>
	</PropertyGroup>

	<Target Name="WarnIfMissingResource" BeforeTargets="BeforeBuild">
		<Warning Condition="!Exists('APIKEY')" Text="Warning: You need a file named 'APIKEY' in the Calculator folder with an api key to use the openexchangerates.org API." />
	</Target>

	<ItemGroup Condition="Exists('APIKEY')">
		<EmbeddedResource Include="APIKEY" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
		<PackageReference Include="Xamarin.Plugins.Clipboard" Version="2.3.0"/>
		<TrimmerRootAssembly Include="Plugin.Clipboard" RootMode="All" />
	</ItemGroup>

</Project>
