<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<PublishSelfContained>true</PublishSelfContained>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>full</TrimMode>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<InvariantGlobalization>true</InvariantGlobalization>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<OutputType>WinExe</OutputType>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<UseWPF>false</UseWPF>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' != 'net10.0-windows'">
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../Calculator/Calculator.csproj" />
	</ItemGroup>

</Project>
